# 文件上传配置
spring:
  servlet:
    multipart:
      enabled: true # 开启文件上传支持（默认已开启）
      max-file-size: 10MB # 单个文件最大上传大小（可自定义，如50MB、1GB）
      max-request-size: 100MB # 单次请求（多文件上传）的总大小最大值
      file-size-threshold: 2MB # 文件大小超过该值时，会临时写入磁盘（默认0，即所有文件都临时写入磁盘）